from pericode_fork.artificial_data import decaying_multi_normal
from pericode_fork.cifar10 import Cifar10
from pericode_fork.hierarchical import Hierarchical
from pericode_fork.imagedata import ImageData
from pericode_fork.top_down import TopDownPrediction 
from pericode_fork.regimens import EMRegimen